export const mockTransactionList = [
  {
    id: 1,
    description: "Salário de março",
    amount: 1850.0,
    type: "income",
    category: "Salário",
    date: "2024-03-25",
  },
  {
    id: 2,
    description: "Renda do apartamento",
    amount: 650.0,
    type: "expense",
    category: "Habitação",
    date: "2024-03-26",
  },
  {
    id: 3,
    description: "Supermercado Pingo Doce",
    amount: 87.4,
    type: "expense",
    category: "Alimentação",
    date: "2024-03-27",
  },
  {
    id: 4,
    description: "Trabalho freelance",
    amount: 320.0,
    type: "income",
    category: "Trabalho Extra",
    date: "2024-03-28",
  },
  {
    id: 5,
    description: "NOS - internet e telemóvel",
    amount: 45.0,
    type: "expense",
    category: "Serviços",
    date: "2024-03-29",
  },
  {
    id: 6,
    description: "Jantar com clientes",
    amount: 112.8,
    type: "expense",
    category: "Lazer",
    date: "2024-03-30",
  },
  {
    id: 7,
    description: "Reembolso de viagem",
    amount: 95.0,
    type: "income",
    category: "Reembolsos",
    date: "2024-03-31",
  },
  {
    id: 8,
    description: "Ginásio Holmes Place",
    amount: 39.9,
    type: "expense",
    category: "Saúde/Fitness",
    date: "2024-04-01",
  },
];

export const mockCategoryList = [
  {
    slug: "alimentacao",
    label: "Alimentação",
    labelEn: "Food & Dining",
    color: "#F97316",
    iconUrl: "/api/categories/alimentacao/icon",
  },
  {
    slug: "transporte",
    label: "Transporte",
    labelEn: "Transportation",
    color: "#3B82F6",
    iconUrl: "/api/categories/transporte/icon",
  },
  {
    slug: "saude",
    label: "Saúde",
    labelEn: "Health",
    color: "#EF4444",
    iconUrl: "/api/categories/saude/icon",
  },
  {
    slug: "bem-estar",
    label: "Bem-estar",
    labelEn: "Wellness & Gym",
    color: "#8B5CF6",
    iconUrl: "/api/categories/bem-estar/icon",
  },
  {
    slug: "habitacao",
    label: "Habitação",
    labelEn: "Housing & Rent",
    color: "#10B981",
    iconUrl: "/api/categories/habitacao/icon",
  },
  {
    slug: "lazer",
    label: "Lazer",
    labelEn: "Entertainment",
    color: "#F59E0B",
    iconUrl: "/api/categories/lazer/icon",
  },
  {
    slug: "compras",
    label: "Compras",
    labelEn: "Shopping",
    color: "#EC4899",
    iconUrl: "/api/categories/compras/icon",
  },
  {
    slug: "educacao",
    label: "Educação",
    labelEn: "Education",
    color: "#06B6D4",
    iconUrl: "/api/categories/educacao/icon",
  },
  {
    slug: "tecnologia",
    label: "Tecnologia",
    labelEn: "Technology",
    color: "#6366F1",
    iconUrl: "/api/categories/tecnologia/icon",
  },
  {
    slug: "viagens",
    label: "Viagens",
    labelEn: "Travel",
    color: "#14B8A6",
    iconUrl: "/api/categories/viagens/icon",
  },
  {
    slug: "restaurantes",
    label: "Restaurantes",
    labelEn: "Restaurants & Bars",
    color: "#F97316",
    iconUrl: "/api/categories/restaurantes/icon",
  },
  {
    slug: "outro",
    label: "Outro",
    labelEn: "Other",
    color: "#6B7280",
    iconUrl: "/api/categories/outro/icon",
  },
];
