export const initialTransactions = [
  {
    id: 1,
    description: "Salário de março",
    amount: 1850.0,
    type: "income",
    category: "Salário",
    date: "2024-03-25",
    fulfilled: true,
  },
  {
    id: 2,
    description: "Renda do apartamento",
    amount: 650.0,
    type: "expense",
    category: "Habitação",
    date: "2024-03-26",
    fulfilled: true,
  },
  {
    id: 3,
    description: "Supermercado Pingo Doce",
    amount: 87.4,
    type: "expense",
    category: "Alimentação",
    date: "2024-03-27",
    fulfilled: true,
  },
  {
    id: 4,
    description: "Trabalho freelance",
    amount: 320.0,
    type: "income",
    category: "Trabalho Extra",
    date: "2024-03-28",
    fulfilled: true,
  },
  {
    id: 5,
    description: "NOS - internet e telemóvel",
    amount: 45.0,
    type: "expense",
    category: "Serviços",
    date: "2024-03-29",
    fulfilled: false,
  },
  {
    id: 6,
    description: "Jantar com clientes",
    amount: 112.8,
    type: "expense",
    category: "Lazer",
    date: "2024-03-30",
    fulfilled: true,
  },
  {
    id: 7,
    description: "Reembolso de viagem",
    amount: 95.0,
    type: "income",
    category: "Reembolsos",
    date: "2024-03-31",
    fulfilled: true,
  },
  {
    id: 8,
    description: "Ginásio Holmes Place",
    amount: 39.9,
    type: "expense",
    category: "Saúde/Fitness",
    date: "2024-04-01",
    fulfilled: false,
  },
];